FROM nvidia/cuda:11.4.1-cudnn8-runtime-ubuntu18.04


ENV TZ=America/Sao_Paulo
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone

RUN apt -y update && \
    apt -y install  python3-pip nvidia-utils-515 nvidia-driver-515


RUN pip3 install --upgrade pip && \
    pip3 install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
